# Keep GitHub Actions up to date
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Montevideo"
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automated"
